kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs