apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-es-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /d/nfsroot/esdata
    server: 192.168.3.150