apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-es-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /var/nfsroot/es_data
    server: 192.168.3.127