version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - cluster.name=xd-esc
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
    volumes:
      - D:/es_data/es_data1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es02
    environment:
      - cluster.name=xd-esc
      - node.name=es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
    volumes:
      - D:/es_data/es_data2:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
      http.host: "0.0.0.0"
      I18N_LOCALE: zh-CN
      XPACK_GRAPH_ENABLED: "true"
      IMELION_ENABLED: "true"
    networks:
      - elastic

  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://es01:9200
    networks:
      - elastic

#  logstash01:
#    image: docker.elastic.co/logstash/logstash:7.6.2
#    container_name: logstash01
#    ports: 
#      - 5044:5044
#    volumes:
#      - ./logstash-pipeline/:/usr/share/logstash/pipeline/
#      - ./logstash-config/logstash.yml:/usr/share/logstash/config/logstash.yml
#    environment:
#      ELASTICSEARCH_URL: http://es01:9200
#      ELASTICSEARCH_HOSTS: http://es01:9200
#    networks:
#      - elastic    


networks:
  elastic:
    driver: bridge
