apiVersion: v1
kind: PersistentVolume
metadata:
  name: espv2
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /d/nfsroot/es-logging2
    server: 192.168.3.150