apiVersion: v1
kind: PersistentVolume
metadata:
  name: espv1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /d/nfsroot/es-logging
    server: 192.168.3.150