kind: Pod
apiVersion: v1
metadata:
  name: xdu
spec:
  containers:
  - name: xdu
    image: ubuntu:latest
    command:
      - "/bin/sh"
    args:
      - "-c"
#      - "touch /mnt/SUCCESS && exit 0 || exit 1"
      - "echo hello > /mnt/aa.txt && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: pvc-es-master

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-es-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
