apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /d/nfsroot/testFolder1
    server: 192.168.3.150